# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import audio_pb2 as llmcore_dot_v1_dot_audio__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/llmcore.v1.AudioService/Synthesize',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.SpeechResult.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/llmcore.v1.AudioService/Transcribe',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.TranscriptionResult.FromString,
                _registered_method=True)
        self.GenerateImage = channel.unary_unary(
                '/llmcore.v1.AudioService/GenerateImage',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.ImageGenerationResult.FromString,
                _registered_method=True)
        self.Ocr = channel.unary_unary(
                '/llmcore.v1.AudioService/Ocr',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.OcrRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.OCRResult.FromString,
                _registered_method=True)
        self.AnalyzeText = channel.unary_unary(
                '/llmcore.v1.AudioService/AnalyzeText',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.AnalyzeTextRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.TextAnalysisResult.FromString,
                _registered_method=True)
        self.TranscribeStream = channel.stream_stream(
                '/llmcore.v1.AudioService/TranscribeStream',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.AudioIn.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.TranscriptionStreamEvent.FromString,
                _registered_method=True)
        self.SynthesizeStream = channel.stream_stream(
                '/llmcore.v1.AudioService/SynthesizeStream',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.SynthControl.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.AudioOut.FromString,
                _registered_method=True)
        self.VoiceAgent = channel.stream_stream(
                '/llmcore.v1.AudioService/VoiceAgent',
                request_serializer=llmcore_dot_v1_dot_audio__pb2.VoiceAgentClientEvent.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_audio__pb2.VoiceAgentEvent.FromString,
                _registered_method=True)


class AudioServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """One-shot (unary)
        generate_speech (base.py:253)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """transcribe_audio (base.py:285)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """generate_image (base.py:319)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ocr(self, request, context):
        """ocr (base.py:354)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeText(self, request, context):
        """analyze_text (deepgram_provider.py:2010)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeStream(self, request_iterator, context):
        """Live streaming (B3)
        deepgram_provider.py:1275
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeStream(self, request_iterator, context):
        """deepgram_provider.py:1535
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceAgent(self, request_iterator, context):
        """deepgram_provider.py:1875
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.SynthesizeRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.SpeechResult.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.TranscribeRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.TranscriptionResult.SerializeToString,
            ),
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.GenerateImageRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.ImageGenerationResult.SerializeToString,
            ),
            'Ocr': grpc.unary_unary_rpc_method_handler(
                    servicer.Ocr,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.OcrRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.OCRResult.SerializeToString,
            ),
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.AnalyzeTextRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.TextAnalysisResult.SerializeToString,
            ),
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.AudioIn.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.TranscriptionStreamEvent.SerializeToString,
            ),
            'SynthesizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.SynthControl.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.AudioOut.SerializeToString,
            ),
            'VoiceAgent': grpc.stream_stream_rpc_method_handler(
                    servicer.VoiceAgent,
                    request_deserializer=llmcore_dot_v1_dot_audio__pb2.VoiceAgentClientEvent.FromString,
                    response_serializer=llmcore_dot_v1_dot_audio__pb2.VoiceAgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.AudioService/Synthesize',
            llmcore_dot_v1_dot_audio__pb2.SynthesizeRequest.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.SpeechResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.AudioService/Transcribe',
            llmcore_dot_v1_dot_audio__pb2.TranscribeRequest.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.TranscriptionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.AudioService/GenerateImage',
            llmcore_dot_v1_dot_audio__pb2.GenerateImageRequest.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.ImageGenerationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ocr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.AudioService/Ocr',
            llmcore_dot_v1_dot_audio__pb2.OcrRequest.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.OCRResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.AudioService/AnalyzeText',
            llmcore_dot_v1_dot_audio__pb2.AnalyzeTextRequest.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.TextAnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/llmcore.v1.AudioService/TranscribeStream',
            llmcore_dot_v1_dot_audio__pb2.AudioIn.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.TranscriptionStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/llmcore.v1.AudioService/SynthesizeStream',
            llmcore_dot_v1_dot_audio__pb2.SynthControl.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.AudioOut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoiceAgent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/llmcore.v1.AudioService/VoiceAgent',
            llmcore_dot_v1_dot_audio__pb2.VoiceAgentClientEvent.SerializeToString,
            llmcore_dot_v1_dot_audio__pb2.VoiceAgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
