# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import catalog_pb2 as llmcore_dot_v1_dot_catalog__pb2
from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProviders = channel.unary_unary(
                '/llmcore.v1.CatalogService/ListProviders',
                request_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_catalog__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/llmcore.v1.CatalogService/ListModels',
                request_serializer=llmcore_dot_v1_dot_catalog__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_catalog__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetProviderDetails = channel.unary_unary(
                '/llmcore.v1.CatalogService/GetProviderDetails',
                request_serializer=llmcore_dot_v1_dot_catalog__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_catalog__pb2.ModelDetails.FromString,
                _registered_method=True)


class CatalogServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListProviders(self, request, context):
        """LLMCore.get_available_providers (api.py:598)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """LLMCore.get_models_for_provider (api.py:3078)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderDetails(self, request, context):
        """LLMCore.get_provider_details (api.py:906)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=llmcore_dot_v1_dot_catalog__pb2.ListProvidersResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=llmcore_dot_v1_dot_catalog__pb2.ListModelsRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_catalog__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetProviderDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderDetails,
                    request_deserializer=llmcore_dot_v1_dot_catalog__pb2.GetProviderRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_catalog__pb2.ModelDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.CatalogService/ListProviders',
            llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            llmcore_dot_v1_dot_catalog__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.CatalogService/ListModels',
            llmcore_dot_v1_dot_catalog__pb2.ListModelsRequest.SerializeToString,
            llmcore_dot_v1_dot_catalog__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.CatalogService/GetProviderDetails',
            llmcore_dot_v1_dot_catalog__pb2.GetProviderRequest.SerializeToString,
            llmcore_dot_v1_dot_catalog__pb2.ModelDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
