# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmcore/v1/catalog.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llmcore/v1/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18llmcore/v1/catalog.proto\x12\nllmcore.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17llmcore/v1/common.proto\"\xa3\x04\n\x0cModelDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rprovider_name\x18\x02 \x01(\t\x12\x19\n\x0c\x64isplay_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x16\n\x0e\x63ontext_length\x18\x04 \x01(\x05\x12\x1e\n\x11max_output_tokens\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\x12supports_streaming\x18\x06 \x01(\x08\x12\x16\n\x0esupports_tools\x18\x07 \x01(\x08\x12\x17\n\x0fsupports_vision\x18\x08 \x01(\x08\x12\x1a\n\x12supports_reasoning\x18\t \x01(\x08\x12\x13\n\x06\x66\x61mily\x18\n \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0fparameter_count\x18\x0b \x01(\tH\x03\x88\x01\x01\x12\x1f\n\x12quantization_level\x18\x0c \x01(\tH\x04\x88\x01\x01\x12\x1c\n\x0f\x66ile_size_bytes\x18\r \x01(\x03H\x05\x88\x01\x01\x12\x17\n\nmodel_type\x18\x0e \x01(\tH\x06\x88\x01\x01\x12)\n\x08metadata\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructB\x0f\n\r_display_nameB\x14\n\x12_max_output_tokensB\t\n\x07_familyB\x12\n\x10_parameter_countB\x15\n\x13_quantization_levelB\x12\n\x10_file_size_bytesB\r\n\x0b_model_type\"*\n\x15ListProvidersResponse\x12\x11\n\tproviders\x18\x01 \x03(\t\"*\n\x11ListModelsRequest\x12\x15\n\rprovider_name\x18\x01 \x01(\t\"$\n\x12ListModelsResponse\x12\x0e\n\x06models\x18\x01 \x03(\t\"B\n\x12GetProviderRequest\x12\x1a\n\rprovider_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_provider_name2\xf4\x01\n\x0e\x43\x61talogService\x12\x45\n\rListProviders\x12\x11.llmcore.v1.Empty\x1a!.llmcore.v1.ListProvidersResponse\x12K\n\nListModels\x12\x1d.llmcore.v1.ListModelsRequest\x1a\x1e.llmcore.v1.ListModelsResponse\x12N\n\x12GetProviderDetails\x12\x1e.llmcore.v1.GetProviderRequest\x1a\x18.llmcore.v1.ModelDetailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmcore.v1.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELDETAILS']._serialized_start=96
  _globals['_MODELDETAILS']._serialized_end=643
  _globals['_LISTPROVIDERSRESPONSE']._serialized_start=645
  _globals['_LISTPROVIDERSRESPONSE']._serialized_end=687
  _globals['_LISTMODELSREQUEST']._serialized_start=689
  _globals['_LISTMODELSREQUEST']._serialized_end=731
  _globals['_LISTMODELSRESPONSE']._serialized_start=733
  _globals['_LISTMODELSRESPONSE']._serialized_end=769
  _globals['_GETPROVIDERREQUEST']._serialized_start=771
  _globals['_GETPROVIDERREQUEST']._serialized_end=837
  _globals['_CATALOGSERVICE']._serialized_start=840
  _globals['_CATALOGSERVICE']._serialized_end=1084
# @@protoc_insertion_point(module_scope)
