# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmcore/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llmcore/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17llmcore/v1/common.proto\x12\nllmcore.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x07\n\x05\x45mpty\"\xbe\x01\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x1e\n\x04role\x18\x03 \x01(\x0e\x32\x10.llmcore.v1.Role\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x06 \x01(\t\x12\x0e\n\x06tokens\x18\x07 \x01(\x05\x12)\n\x08metadata\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\"V\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12+\n\nparameters\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"P\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\targuments\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"E\n\nToolResult\x12\x14\n\x0ctool_call_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08is_error\x18\x03 \x01(\x08\"\xd9\x01\n\x05Usage\x12\x1a\n\rprompt_tokens\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1e\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x19\n\x0ctotal_tokens\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x15\n\x08provider\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05model\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x10\n\x0e_prompt_tokensB\x14\n\x12_completion_tokensB\x0f\n\r_total_tokensB\x0b\n\t_providerB\x08\n\x06_model\",\n\x0b\x46loatVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05index\x18\x02 \x01(\x05*_\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bROLE_SYSTEM\x10\x01\x12\r\n\tROLE_USER\x10\x02\x12\x12\n\x0eROLE_ASSISTANT\x10\x03\x12\r\n\tROLE_TOOL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmcore.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=778
  _globals['_ROLE']._serialized_end=873
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_MESSAGE']._serialized_start=79
  _globals['_MESSAGE']._serialized_end=269
  _globals['_TOOL']._serialized_start=271
  _globals['_TOOL']._serialized_end=357
  _globals['_TOOLCALL']._serialized_start=359
  _globals['_TOOLCALL']._serialized_end=439
  _globals['_TOOLRESULT']._serialized_start=441
  _globals['_TOOLRESULT']._serialized_end=510
  _globals['_USAGE']._serialized_start=513
  _globals['_USAGE']._serialized_end=730
  _globals['_FLOATVECTOR']._serialized_start=732
  _globals['_FLOATVECTOR']._serialized_end=776
# @@protoc_insertion_point(module_scope)
