# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmcore/v1/control.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llmcore/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18llmcore/v1/control.proto\x12\nllmcore.v1\x1a\x17llmcore/v1/common.proto\"/\n\x0cProviderInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x08\"\xbd\x01\n\nServerInfo\x12\x17\n\x0fllmcore_version\x18\x01 \x01(\t\x12\x16\n\x0e\x62ridge_version\x18\x02 \x01(\t\x12\x18\n\x10\x63ontract_version\x18\x03 \x01(\t\x12\x12\n\ntransports\x18\x04 \x03(\t\x12+\n\tproviders\x18\x05 \x03(\x0b\x32\x18.llmcore.v1.ProviderInfo\x12\x14\n\x0c\x63\x61pabilities\x18\x06 \x03(\t\x12\r\n\x05tiers\x18\x07 \x03(\t\"*\n\x0cHealthStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"1\n\x13ReloadConfigRequest\x12\x11\n\x04path\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_path\"\"\n\x14ReloadConfigResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xd0\x01\n\x0e\x43ontrolService\x12\x34\n\x07GetInfo\x12\x11.llmcore.v1.Empty\x1a\x16.llmcore.v1.ServerInfo\x12\x35\n\x06Health\x12\x11.llmcore.v1.Empty\x1a\x18.llmcore.v1.HealthStatus\x12Q\n\x0cReloadConfig\x12\x1f.llmcore.v1.ReloadConfigRequest\x1a .llmcore.v1.ReloadConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmcore.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVIDERINFO']._serialized_start=65
  _globals['_PROVIDERINFO']._serialized_end=112
  _globals['_SERVERINFO']._serialized_start=115
  _globals['_SERVERINFO']._serialized_end=304
  _globals['_HEALTHSTATUS']._serialized_start=306
  _globals['_HEALTHSTATUS']._serialized_end=348
  _globals['_RELOADCONFIGREQUEST']._serialized_start=350
  _globals['_RELOADCONFIGREQUEST']._serialized_end=399
  _globals['_RELOADCONFIGRESPONSE']._serialized_start=401
  _globals['_RELOADCONFIGRESPONSE']._serialized_end=435
  _globals['_CONTROLSERVICE']._serialized_start=438
  _globals['_CONTROLSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
