# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmcore/v1/errors.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llmcore/v1/errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17llmcore/v1/errors.proto\x12\nllmcore.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb3\x02\n\x0cLlmcoreError\x12+\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\x19.llmcore.v1.ErrorCategory\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x15\n\x08provider\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05model\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bhttp_status\x18\x06 \x01(\x05H\x02\x88\x01\x01\x12\x11\n\tretryable\x18\x07 \x01(\x08\x12\x1b\n\x0eretry_after_ms\x18\x08 \x01(\x01H\x03\x88\x01\x01\x12(\n\x07\x64\x65tails\x18\t \x01(\x0b\x32\x17.google.protobuf.StructB\x0b\n\t_providerB\x08\n\x06_modelB\x0e\n\x0c_http_statusB\x11\n\x0f_retry_after_ms*\x99\x03\n\rErrorCategory\x12\x1e\n\x1a\x45RROR_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45RROR_CATEGORY_PROVIDER\x10\x01\x12\x19\n\x15\x45RROR_CATEGORY_CONFIG\x10\x02\x12!\n\x1d\x45RROR_CATEGORY_CONTEXT_LENGTH\x10\x03\x12\x1a\n\x16\x45RROR_CATEGORY_CONTEXT\x10\x04\x12\x1c\n\x18\x45RROR_CATEGORY_EMBEDDING\x10\x05\x12\x1a\n\x16\x45RROR_CATEGORY_STORAGE\x10\x06\x12\x1c\n\x18\x45RROR_CATEGORY_NOT_FOUND\x10\x07\x12\x19\n\x15\x45RROR_CATEGORY_SEARCH\x10\x08\x12\x1e\n\x1a\x45RROR_CATEGORY_UNSUPPORTED\x10\t\x12\x1c\n\x18\x45RROR_CATEGORY_CANCELLED\x10\n\x12\x1b\n\x17\x45RROR_CATEGORY_INTERNAL\x10\x0b\x12#\n\x1f\x45RROR_CATEGORY_INVALID_ARGUMENT\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmcore.v1.errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCATEGORY']._serialized_start=380
  _globals['_ERRORCATEGORY']._serialized_end=789
  _globals['_LLMCOREERROR']._serialized_start=70
  _globals['_LLMCOREERROR']._serialized_end=377
# @@protoc_insertion_point(module_scope)
