# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import inference_pb2 as llmcore_dot_v1_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/llmcore.v1.InferenceService/Chat',
                request_serializer=llmcore_dot_v1_dot_inference__pb2.ChatRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_inference__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/llmcore.v1.InferenceService/ChatStream',
                request_serializer=llmcore_dot_v1_dot_inference__pb2.ChatRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_inference__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/llmcore.v1.InferenceService/Embed',
                request_serializer=llmcore_dot_v1_dot_inference__pb2.EmbedRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_inference__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.CountTokens = channel.unary_unary(
                '/llmcore.v1.InferenceService/CountTokens',
                request_serializer=llmcore_dot_v1_dot_inference__pb2.CountTokensRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_inference__pb2.CountTokensResponse.FromString,
                _registered_method=True)
        self.EstimateCost = channel.unary_unary(
                '/llmcore.v1.InferenceService/EstimateCost',
                request_serializer=llmcore_dot_v1_dot_inference__pb2.EstimateCostRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_inference__pb2.CostEstimate.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """UNIMPLEMENTED in v1 (no public facade path)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=llmcore_dot_v1_dot_inference__pb2.ChatRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_inference__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=llmcore_dot_v1_dot_inference__pb2.ChatRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_inference__pb2.ChatChunk.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=llmcore_dot_v1_dot_inference__pb2.EmbedRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_inference__pb2.EmbedResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=llmcore_dot_v1_dot_inference__pb2.CountTokensRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_inference__pb2.CountTokensResponse.SerializeToString,
            ),
            'EstimateCost': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateCost,
                    request_deserializer=llmcore_dot_v1_dot_inference__pb2.EstimateCostRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_inference__pb2.CostEstimate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.InferenceService/Chat',
            llmcore_dot_v1_dot_inference__pb2.ChatRequest.SerializeToString,
            llmcore_dot_v1_dot_inference__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llmcore.v1.InferenceService/ChatStream',
            llmcore_dot_v1_dot_inference__pb2.ChatRequest.SerializeToString,
            llmcore_dot_v1_dot_inference__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.InferenceService/Embed',
            llmcore_dot_v1_dot_inference__pb2.EmbedRequest.SerializeToString,
            llmcore_dot_v1_dot_inference__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.InferenceService/CountTokens',
            llmcore_dot_v1_dot_inference__pb2.CountTokensRequest.SerializeToString,
            llmcore_dot_v1_dot_inference__pb2.CountTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.InferenceService/EstimateCost',
            llmcore_dot_v1_dot_inference__pb2.EstimateCostRequest.SerializeToString,
            llmcore_dot_v1_dot_inference__pb2.CostEstimate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
