# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2
from llmcore.bridge._generated.llmcore.v1 import presets_pb2 as llmcore_dot_v1_dot_presets__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/presets_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresetServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveContextPreset = channel.unary_unary(
                '/llmcore.v1.PresetService/SaveContextPreset',
                request_serializer=llmcore_dot_v1_dot_presets__pb2.SaveContextPresetRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.GetContextPreset = channel.unary_unary(
                '/llmcore.v1.PresetService/GetContextPreset',
                request_serializer=llmcore_dot_v1_dot_presets__pb2.GetContextPresetRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_presets__pb2.ContextPreset.FromString,
                _registered_method=True)
        self.ListContextPresets = channel.unary_unary(
                '/llmcore.v1.PresetService/ListContextPresets',
                request_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_presets__pb2.ListContextPresetsResponse.FromString,
                _registered_method=True)
        self.DeleteContextPreset = channel.unary_unary(
                '/llmcore.v1.PresetService/DeleteContextPreset',
                request_serializer=llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetResponse.FromString,
                _registered_method=True)


class PresetServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SaveContextPreset(self, request, context):
        """LLMCore.save_context_preset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContextPreset(self, request, context):
        """LLMCore.get_context_preset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContextPresets(self, request, context):
        """LLMCore.list_context_presets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteContextPreset(self, request, context):
        """LLMCore.delete_context_preset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveContextPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveContextPreset,
                    request_deserializer=llmcore_dot_v1_dot_presets__pb2.SaveContextPresetRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'GetContextPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContextPreset,
                    request_deserializer=llmcore_dot_v1_dot_presets__pb2.GetContextPresetRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_presets__pb2.ContextPreset.SerializeToString,
            ),
            'ListContextPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContextPresets,
                    request_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=llmcore_dot_v1_dot_presets__pb2.ListContextPresetsResponse.SerializeToString,
            ),
            'DeleteContextPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteContextPreset,
                    request_deserializer=llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.PresetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.PresetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresetService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveContextPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.PresetService/SaveContextPreset',
            llmcore_dot_v1_dot_presets__pb2.SaveContextPresetRequest.SerializeToString,
            llmcore_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContextPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.PresetService/GetContextPreset',
            llmcore_dot_v1_dot_presets__pb2.GetContextPresetRequest.SerializeToString,
            llmcore_dot_v1_dot_presets__pb2.ContextPreset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContextPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.PresetService/ListContextPresets',
            llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            llmcore_dot_v1_dot_presets__pb2.ListContextPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteContextPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.PresetService/DeleteContextPreset',
            llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetRequest.SerializeToString,
            llmcore_dot_v1_dot_presets__pb2.DeleteContextPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
