# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmcore/v1/presets.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llmcore/v1/presets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18llmcore/v1/presets.proto\x12\nllmcore.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17llmcore/v1/common.proto\"\xb5\x01\n\x11\x43ontextPresetItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x14\n\x07\x63ontent\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x11source_identifier\x18\x04 \x01(\tH\x01\x88\x01\x01\x12)\n\x08metadata\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructB\n\n\x08_contentB\x14\n\x12_source_identifier\"\xc8\x01\n\rContextPreset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00\x88\x01\x01\x12,\n\x05items\x18\x03 \x03(\x0b\x32\x1d.llmcore.v1.ContextPresetItem\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructB\x0e\n\x0c_description\"E\n\x18SaveContextPresetRequest\x12)\n\x06preset\x18\x01 \x01(\x0b\x32\x19.llmcore.v1.ContextPreset\".\n\x17GetContextPresetRequest\x12\x13\n\x0bpreset_name\x18\x01 \x01(\t\"F\n\x1aListContextPresetsResponse\x12(\n\x07presets\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\"1\n\x1a\x44\x65leteContextPresetRequest\x12\x13\n\x0bpreset_name\x18\x01 \x01(\t\".\n\x1b\x44\x65leteContextPresetResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xea\x02\n\rPresetService\x12L\n\x11SaveContextPreset\x12$.llmcore.v1.SaveContextPresetRequest\x1a\x11.llmcore.v1.Empty\x12R\n\x10GetContextPreset\x12#.llmcore.v1.GetContextPresetRequest\x1a\x19.llmcore.v1.ContextPreset\x12O\n\x12ListContextPresets\x12\x11.llmcore.v1.Empty\x1a&.llmcore.v1.ListContextPresetsResponse\x12\x66\n\x13\x44\x65leteContextPreset\x12&.llmcore.v1.DeleteContextPresetRequest\x1a\'.llmcore.v1.DeleteContextPresetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmcore.v1.presets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTPRESETITEM']._serialized_start=96
  _globals['_CONTEXTPRESETITEM']._serialized_end=277
  _globals['_CONTEXTPRESET']._serialized_start=280
  _globals['_CONTEXTPRESET']._serialized_end=480
  _globals['_SAVECONTEXTPRESETREQUEST']._serialized_start=482
  _globals['_SAVECONTEXTPRESETREQUEST']._serialized_end=551
  _globals['_GETCONTEXTPRESETREQUEST']._serialized_start=553
  _globals['_GETCONTEXTPRESETREQUEST']._serialized_end=599
  _globals['_LISTCONTEXTPRESETSRESPONSE']._serialized_start=601
  _globals['_LISTCONTEXTPRESETSRESPONSE']._serialized_end=671
  _globals['_DELETECONTEXTPRESETREQUEST']._serialized_start=673
  _globals['_DELETECONTEXTPRESETREQUEST']._serialized_end=722
  _globals['_DELETECONTEXTPRESETRESPONSE']._serialized_start=724
  _globals['_DELETECONTEXTPRESETRESPONSE']._serialized_end=770
  _globals['_PRESETSERVICE']._serialized_start=773
  _globals['_PRESETSERVICE']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
