# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2
from llmcore.bridge._generated.llmcore.v1 import sessions_pb2 as llmcore_dot_v1_dot_sessions__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/sessions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/llmcore.v1.SessionService/CreateSession',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.ChatSession.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/llmcore.v1.SessionService/GetSession',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.ChatSession.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/llmcore.v1.SessionService/ListSessions',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/llmcore.v1.SessionService/DeleteSession',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateSessionName = channel.unary_unary(
                '/llmcore.v1.SessionService/UpdateSessionName',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.UpdateSessionNameRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.ForkSession = channel.unary_unary(
                '/llmcore.v1.SessionService/ForkSession',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.ForkSessionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.ForkSessionResponse.FromString,
                _registered_method=True)
        self.CloneSession = channel.unary_unary(
                '/llmcore.v1.SessionService/CloneSession',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.CloneSessionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.CloneSessionResponse.FromString,
                _registered_method=True)
        self.DeleteMessages = channel.unary_unary(
                '/llmcore.v1.SessionService/DeleteMessages',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesResponse.FromString,
                _registered_method=True)
        self.GetMessagesByRange = channel.unary_unary(
                '/llmcore.v1.SessionService/GetMessagesByRange',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeResponse.FromString,
                _registered_method=True)
        self.AddContextItem = channel.unary_unary(
                '/llmcore.v1.SessionService/AddContextItem',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.AddContextItemRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.AddContextItemResponse.FromString,
                _registered_method=True)
        self.GetContextItem = channel.unary_unary(
                '/llmcore.v1.SessionService/GetContextItem',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.GetContextItemRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.ContextItem.FromString,
                _registered_method=True)
        self.RemoveContextItem = channel.unary_unary(
                '/llmcore.v1.SessionService/RemoveContextItem',
                request_serializer=llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemResponse.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """LLMCore.create_session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """LLMCore.get_session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """LLMCore.list_sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """LLMCore.delete_session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionName(self, request, context):
        """LLMCore.update_session_name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkSession(self, request, context):
        """LLMCore.fork_session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneSession(self, request, context):
        """LLMCore.clone_session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessages(self, request, context):
        """LLMCore.delete_messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessagesByRange(self, request, context):
        """LLMCore.get_messages_by_range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddContextItem(self, request, context):
        """LLMCore.add_context_item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContextItem(self, request, context):
        """LLMCore.get_context_item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContextItem(self, request, context):
        """LLMCore.remove_context_item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.CreateSessionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.ChatSession.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.GetSessionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.ChatSession.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.ListSessionsRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.DeleteSessionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'UpdateSessionName': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionName,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.UpdateSessionNameRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'ForkSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkSession,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.ForkSessionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.ForkSessionResponse.SerializeToString,
            ),
            'CloneSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneSession,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.CloneSessionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.CloneSessionResponse.SerializeToString,
            ),
            'DeleteMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessages,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesResponse.SerializeToString,
            ),
            'GetMessagesByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessagesByRange,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeResponse.SerializeToString,
            ),
            'AddContextItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContextItem,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.AddContextItemRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.AddContextItemResponse.SerializeToString,
            ),
            'GetContextItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContextItem,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.GetContextItemRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.ContextItem.SerializeToString,
            ),
            'RemoveContextItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContextItem,
                    request_deserializer=llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/CreateSession',
            llmcore_dot_v1_dot_sessions__pb2.CreateSessionRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.ChatSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/GetSession',
            llmcore_dot_v1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.ChatSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/ListSessions',
            llmcore_dot_v1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/DeleteSession',
            llmcore_dot_v1_dot_sessions__pb2.DeleteSessionRequest.SerializeToString,
            llmcore_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/UpdateSessionName',
            llmcore_dot_v1_dot_sessions__pb2.UpdateSessionNameRequest.SerializeToString,
            llmcore_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/ForkSession',
            llmcore_dot_v1_dot_sessions__pb2.ForkSessionRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.ForkSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloneSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/CloneSession',
            llmcore_dot_v1_dot_sessions__pb2.CloneSessionRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.CloneSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/DeleteMessages',
            llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.DeleteMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessagesByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/GetMessagesByRange',
            llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.GetMessagesByRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddContextItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/AddContextItem',
            llmcore_dot_v1_dot_sessions__pb2.AddContextItemRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.AddContextItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContextItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/GetContextItem',
            llmcore_dot_v1_dot_sessions__pb2.GetContextItemRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.ContextItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContextItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.SessionService/RemoveContextItem',
            llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemRequest.SerializeToString,
            llmcore_dot_v1_dot_sessions__pb2.RemoveContextItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
