# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmcore.bridge._generated.llmcore.v1 import common_pb2 as llmcore_dot_v1_dot_common__pb2
from llmcore.bridge._generated.llmcore.v1 import vector_pb2 as llmcore_dot_v1_dot_vector__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmcore/v1/vector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDocuments = channel.unary_unary(
                '/llmcore.v1.VectorService/AddDocuments',
                request_serializer=llmcore_dot_v1_dot_vector__pb2.AddDocumentsRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.AddDocumentsResponse.FromString,
                _registered_method=True)
        self.SearchVectorStore = channel.unary_unary(
                '/llmcore.v1.VectorService/SearchVectorStore',
                request_serializer=llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreResponse.FromString,
                _registered_method=True)
        self.ListVectorCollections = channel.unary_unary(
                '/llmcore.v1.VectorService/ListVectorCollections',
                request_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.ListRagCollections = channel.unary_unary(
                '/llmcore.v1.VectorService/ListRagCollections',
                request_serializer=llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.GetRagCollectionInfo = channel.unary_unary(
                '/llmcore.v1.VectorService/GetRagCollectionInfo',
                request_serializer=llmcore_dot_v1_dot_vector__pb2.GetRagCollectionInfoRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.RagCollectionInfo.FromString,
                _registered_method=True)
        self.DeleteRagCollection = channel.unary_unary(
                '/llmcore.v1.VectorService/DeleteRagCollection',
                request_serializer=llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionRequest.SerializeToString,
                response_deserializer=llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionResponse.FromString,
                _registered_method=True)


class VectorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AddDocuments(self, request, context):
        """LLMCore.add_documents_to_vector_store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectorStore(self, request, context):
        """LLMCore.search_vector_store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVectorCollections(self, request, context):
        """LLMCore.list_vector_collections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRagCollections(self, request, context):
        """LLMCore.list_rag_collections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagCollectionInfo(self, request, context):
        """LLMCore.get_rag_collection_info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRagCollection(self, request, context):
        """LLMCore.delete_rag_collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocuments,
                    request_deserializer=llmcore_dot_v1_dot_vector__pb2.AddDocumentsRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.AddDocumentsResponse.SerializeToString,
            ),
            'SearchVectorStore': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectorStore,
                    request_deserializer=llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreResponse.SerializeToString,
            ),
            'ListVectorCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVectorCollections,
                    request_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'ListRagCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRagCollections,
                    request_deserializer=llmcore_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'GetRagCollectionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagCollectionInfo,
                    request_deserializer=llmcore_dot_v1_dot_vector__pb2.GetRagCollectionInfoRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.RagCollectionInfo.SerializeToString,
            ),
            'DeleteRagCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRagCollection,
                    request_deserializer=llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionRequest.FromString,
                    response_serializer=llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmcore.v1.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmcore.v1.VectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/AddDocuments',
            llmcore_dot_v1_dot_vector__pb2.AddDocumentsRequest.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.AddDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectorStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/SearchVectorStore',
            llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreRequest.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.SearchVectorStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVectorCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/ListVectorCollections',
            llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRagCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/ListRagCollections',
            llmcore_dot_v1_dot_common__pb2.Empty.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagCollectionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/GetRagCollectionInfo',
            llmcore_dot_v1_dot_vector__pb2.GetRagCollectionInfoRequest.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.RagCollectionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRagCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmcore.v1.VectorService/DeleteRagCollection',
            llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionRequest.SerializeToString,
            llmcore_dot_v1_dot_vector__pb2.DeleteRagCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
