# src/llmcore/sessions/manager.py
"""
Session Management for LLMCore.

This module defines the SessionManager class, responsible for handling
the lifecycle and state of ChatSession objects, including loading from
and saving to a configured storage backend.
"""

import logging
from typing import Optional

from ..models import ChatSession, Message, Role
from ..storage.base_session import BaseSessionStorage
from ..exceptions import SessionNotFoundError, SessionStorageError, LLMCoreError

logger = logging.getLogger(__name__)


class SessionManager:
    """
    Manages ChatSession objects, interacting with a storage backend.

    Coordinates loading, creating, and saving conversation sessions.
    """

    def __init__(self, storage: BaseSessionStorage):
        """
        Initializes the SessionManager.

        Args:
            storage: An initialized instance of a BaseSessionStorage backend
                     (e.g., JsonSessionStorage, SqliteSessionStorage).
        """
        if not storage:
            # This check ensures storage is provided, preventing None errors later.
            # LLMCore.create should guarantee storage is initialized before SessionManager.
            logger.error("SessionManager initialized without a valid storage backend.")
            raise LLMCoreError("SessionManager requires a valid storage backend instance.")
        self._storage = storage
        logger.debug("SessionManager initialized with storage backend: %s", type(storage).__name__)

    async def load_or_create_session(
        self,
        session_id: Optional[str] = None,
        system_message: Optional[str] = None
    ) -> ChatSession:
        """
        Loads an existing session or creates a new one.

        If session_id is provided:
          - Tries to load the session from storage.
          - If not found, raises SessionNotFoundError.
        If session_id is None:
          - Creates a new, temporary (in-memory) session.
        If system_message is provided *and* a *new* session is created:
          - The system message is added as the first message.

        Args:
            session_id: The ID of the session to load or create. If None,
                        a temporary session is created.
            system_message: An optional system message to add if a new session
                            is created.

        Returns:
            The loaded or newly created ChatSession object.

        Raises:
            SessionNotFoundError: If session_id is provided but not found in storage.
            SessionStorageError: If there's an error interacting with storage.
        """
        if session_id:
            logger.debug(f"Attempting to load session with ID: {session_id}")
            try:
                session = await self._storage.get_session(session_id)
                if session:
                    logger.info(f"Loaded existing session: {session_id}")
                    # Note: We currently don't modify an existing session's system message here.
                    # Behavior for providing system_message with an existing session
                    # could be defined later (e.g., update if different, ignore, error).
                    return session
                else:
                    # Session ID was provided, but not found in storage
                    logger.warning(f"Session ID '{session_id}' provided but not found in storage.")
                    # Specification implies creating if ID provided but not found isn't the default.
                    # Let's raise an error to match LLMCore.chat behavior expectation.
                    raise SessionNotFoundError(session_id)
                    # Alternative: Create a new session with the given ID if desired
                    # logger.info(f"Creating new persistent session with ID: {session_id}")
                    # new_session = ChatSession(session_id=session_id)

            except SessionStorageError as e:
                logger.error(f"Storage error while trying to load session '{session_id}': {e}")
                raise # Re-raise storage errors
            except Exception as e:
                logger.error(f"Unexpected error loading session '{session_id}': {e}", exc_info=True)
                raise SessionStorageError(f"Failed to load session '{session_id}': {e}")

        # If session_id is None, create a new temporary session
        logger.info("Creating new temporary session (session_id is None).")
        # The ID will be generated by ChatSession's default_factory
        new_session = ChatSession()
        if system_message:
            logger.debug("Adding system message to new temporary session.")
            # Use the add_message helper method from ChatSession
            new_session.add_message(message_content=system_message, role=Role.SYSTEM)
            # Note: add_message updates updated_at, which is fine.

        return new_session


    async def save_session(self, session: ChatSession) -> None:
        """
        Saves a session to the configured storage backend.

        Only persistent sessions (those that were loaded or created with a specific ID)
        should typically be saved. Temporary sessions (created when session_id=None)
        are usually not saved unless explicitly given an ID later.

        Args:
            session: The ChatSession object to save.

        Raises:
            SessionStorageError: If there's an error saving the session.
        """
        # We might add a check here: if session.id was generated by default_factory
        # and never explicitly set/loaded, maybe don't save?
        # For now, assume if save_session is called, the intent is to persist.
        logger.debug(f"Attempting to save session: {session.id}")
        try:
            await self._storage.save_session(session)
            logger.info(f"Session '{session.id}' saved successfully.")
        except SessionStorageError as e:
            logger.error(f"Storage error while saving session '{session.id}': {e}")
            raise # Re-raise storage errors
        except Exception as e:
            logger.error(f"Unexpected error saving session '{session.id}': {e}", exc_info=True)
            raise SessionStorageError(f"Failed to save session '{session.id}': {e}")

    # --- Potentially add other methods as needed ---
    # E.g., methods to add messages directly via manager (though adding to the
    # session object itself might be sufficient)
    # async def add_message_to_session(self, session: ChatSession, message: Message): ...
